# Form implementation generated from reading ui file 'juntanomes.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Janela(object):
    def setupUi(self, Janela):
        Janela.setObjectName("Janela")
        Janela.resize(360, 240)
        Janela.setMinimumSize(QtCore.QSize(200, 100))
        Janela.setMaximumSize(QtCore.QSize(800, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Users/1578240/Downloads/lapis.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Janela.setWindowIcon(icon)
        Janela.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(parent=Janela)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_nome = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_nome.setObjectName("label_nome")
        self.verticalLayout.addWidget(self.label_nome)
        self.lineEdit_nome = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.verticalLayout.addWidget(self.lineEdit_nome)
        self.label_sobrenome = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_sobrenome.setObjectName("label_sobrenome")
        self.verticalLayout.addWidget(self.label_sobrenome)
        self.lineEdit_sobrenome = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_sobrenome.setObjectName("lineEdit_sobrenome")
        self.verticalLayout.addWidget(self.lineEdit_sobrenome)
        self.pushButton_juntar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_juntar.setObjectName("pushButton_juntar")
        
        self.pushButton_juntar.clicked.connect(self.juntar)
        
        self.verticalLayout.addWidget(self.pushButton_juntar)
        self.label_completo = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_completo.setObjectName("label_completo")
        self.verticalLayout.addWidget(self.label_completo)
        self.lineEdit_completo = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_completo.setObjectName("lineEdit_completo")
        self.verticalLayout.addWidget(self.lineEdit_completo)
        self.pushButton_limpar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_limpar.setObjectName("pushButton_limpar")
        
        self.pushButton_limpar.clicked.connect(self.limpar)
        
        self.verticalLayout.addWidget(self.pushButton_limpar)
        Janela.setCentralWidget(self.centralwidget)

        self.retranslateUi(Janela)
        QtCore.QMetaObject.connectSlotsByName(Janela)

    def retranslateUi(self, Janela):
        _translate = QtCore.QCoreApplication.translate
        Janela.setWindowTitle(_translate("Janela", "Junta Nomes 1.0"))
        self.label_nome.setText(_translate("Janela", "Nome:"))
        self.label_sobrenome.setText(_translate("Janela", "Sobrenome:"))
        self.pushButton_juntar.setText(_translate("Janela", "JUNTAR"))
        self.label_completo.setText(_translate("Janela", "Nome Completo:"))
        self.pushButton_limpar.setText(_translate("Janela", "LIMPAR"))

    
    def juntar(self):
        nome = self.lineEdit_nome.text()
        sobrenome = self.lineEdit_sobrenome.text()
        self.lineEdit_completo.setText(nome + " " + sobrenome)
    
    def limpar(self):
        self.lineEdit_nome.setText("")
        self.lineEdit_sobrenome.setText("")
        self.lineEdit_completo.setText("")
        
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Janela = QtWidgets.QMainWindow()
    ui = Ui_Janela()
    ui.setupUi(Janela)
    Janela.show()
    sys.exit(app.exec())
